In [1]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [2]:
def column_swap(array: np.array) -> np.array:
  arr = np.fliplr(array)
  return arr

#a = np.array([[1,2,3],[4,3,4],[6,6,4]])
#print(column_swap(a))

In [ ]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [14]:
def compare_two_array(array1: np.array, array2: np.array) -> np.array:
  #return np.all(np.isin(array1, array2)) and np.all(np.isin(array2, array1))
  return np.where(array1 == array2)[0]
  

a = np.array([7,8,9])
b = np.array([9,8,7])
print(compare_two_array(a,b))

[1]


In [ ]:
# Készíts egy olyan függvényt, ami visszaadja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még működnie kell!, 

In [51]:
def get_array_shape(arr: np.array) -> str:
  shape = arr.shape
  if len(shape) == 1:
    return f"sor: 1, oszlop: {shape[0]}, melyseg: 1"    #csak egy elemű tömb, 1x1
  if len(shape) == 2:
    return f"sor: {shape[0]}, oszlop: {shape[1]}, melyseg: 1"   #nxm, de csak 2D
  return f"sor: {shape[1]}, oszlop: {shape[2]}, melyseg: {shape[0]}"  #3d shape (réteg, sor, oszlop)


#n = np.array([1])
#k = np.array([1,2,3])
#a = np.array([[1,2,3], [4,5,6]] )
#z = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#print(get_array_shape(z))


sor: 2, oszlop: 3, melyseg: 2


In [ ]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [55]:
def encode_Y(array: np.array, n_classes: int) -> np.array:
    encoded_y = np.zeros((len(array), n_classes))
    for i in range(len(array)):
        if array[i] != 0:
            encoded_y[i, array[i]-1] = 1
    return encoded_y

#t = np.array([1, 3, 0, 3])
#print(encode_Y(t, 4))

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [59]:
def decode_Y(encoded_y: np.array) -> np.array:
    return np.argmax(encoded_y, axis=1)

#enc = np.array([[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]])
#print(decode_Y(enc))

[1 2 0 3]


In [ ]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

In [61]:
def eval_classification(lista: list, array:np.array) -> str:
    return lista[np.argmax(array)]

#l = ['alma', 'körte', 'szilva']
#a = [0.2, 0.2, 0.6]
#print(eval_classification(l, a))

szilva


In [ ]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()

In [65]:
def replace_odd_numbers(arr:np.array) -> np.array:
    arr[arr % 2 == 1] = -1
    return arr


[-1  2 -1  4 -1  6]


In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [68]:
def replace_by_value(arr: np.array, threshold : int) -> np.array:
  arr[arr < threshold] = -1
  arr[arr >= threshold] = 1
  return arr

#print(replace_by_value(np.array([1, 2, 5, 0]), 2))


[-1  1  1 -1]


In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [70]:
def array_multi(array: np.array) -> int:
  return np.prod(array)



576


In [ ]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [74]:
def array_multi_2d(array: np.array) -> np.array:
  return np.prod(array, axis=1)



[ 2 12]


In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [76]:
def add_border(array: np.array) -> np.array:
  x = np.pad(array, pad_width=1, mode='constant', constant_values=0)
  return x


[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [ ]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
# get_act_date()

In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()